# Generated by Django 5.0.7 on 2024-07-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image4',
        ),
    ]
