# Generated by Django 5.1 on 2024-08-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_confirm_password_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel_and_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TRANSPORTATION', 'Transportation'), ('ACCOMMODATION', 'Accommodation'), ('FOOD', 'Food'), ('SIGHTSEEING', 'Sightseeing and Activities'), ('OVERALL_COST', 'Overall Cost')], max_length=20)),
                ('title', models.CharField(help_text='Title or Name (e.g., By Road, Budget Homestays, etc.)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description or itinerary information.')),
                ('cost', models.CharField(blank=True, help_text='Cost range or pricing information.', max_length=100)),
                ('additional_info', models.TextField(blank=True, help_text='Any additional information related to this entry.')),
            ],
        ),
    ]
