# Generated by Django 5.1 on 2024-09-01 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_travel_and_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_and_cost',
            name='place_name',
            field=models.ForeignKey(default='1', help_text='Name of the place', on_delete=django.db.models.deletion.CASCADE, related_name='travel_and_cost', to='app.place'),
        ),
    ]
