# Generated by Django 5.1 on 2024-09-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_travel_and_cost_place_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='travel_and_cost',
        ),
    ]
