# Generated by Django 5.1 on 2024-09-01 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_travel_and_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_and_cost',
            name='main_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='travel_and_cost', to='app.place'),
        ),
    ]
