# Generated by Django 5.1 on 2024-09-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_travel_and_cost_main_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=10)),
                ('review', models.CharField(max_length=100)),
            ],
        ),
    ]
