# Generated by Django 5.1 on 2024-09-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
    ]
