# Generated by Django 5.1.1 on 2024-09-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_review_location_alter_review_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
